### ISSUE TITLE
`geminiReact is not defined` with gemini update to v4.11.0

### ISSUE THREAD

**Issue by tx44** [researchgate/gemini-react#5]
`gemini` v4.11.0 release is breaking this plugin:

```
Critical error:
ReferenceError: geminiReact is not defined
    at Object.<anonymous> (/Users/teryaew/Projects/common/gemini-react-example/gemini/button.gemini.js:3:1)
    at Module._compile (module.js:556:32)
    at loader (/Users/teryaew/Projects/common/gemini-react-example/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/teryaew/Projects/common/gemini-react-example/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.exports.requireWithNoCache (/Users/teryaew/Projects/common/gemini-react-example/node_modules/gemini/lib/utils.js:5:12)
    at sets.forEachFile (/Users/teryaew/Projects/common/gemini-react-example/node_modules/gemini/lib/test-reader/index.js:22:15)
    at _getFiles.forEach (/Users/teryaew/Projects/common/gemini-react-example/node_modules/gemini/lib/test-reader/set-collection.js:65:44)
    at Array.forEach (native)
    at SetCollection.forEachFile (/Users/teryaew/Projects/common/gemini-react-example/node_modules/gemini/lib/test-reader/set-collection.js:65:26)
    at loadSuites (/Users/teryaew/Projects/common/gemini-react-example/node_modules/gemini/lib/test-reader/index.js:18:10)
    at q.all.spread (/Users/teryaew/Projects/common/gemini-react-example/node_modules/gemini/lib/test-reader/index.js:49:16)
ERROR: "gemini:test" exited with 1.
```

**Comment by SevInf** [comment]
Will be fixed after gemini-testing/gemini#611 is merged.

**Comment by tx44** [comment]
:thumbsup:

**Comment by SevInf** [comment]
@teryaew should work again in gemini 4.11.3
